### ISSUE TITLE
 NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error

### ISSUE THREAD

**Issue by yuehuayingxueluo** [triton-inference-server/tensorrtllm_backend#103]
Hi,
I tried running Llama on 2 A800 Gpus (80GB, Single node), but ran into some nccl errors.
Command: python3 scripts/launch_triton_server.py --world_size=2 --model_repo=/tensorrtllm_backend/triton_model_repo_llama
```bash
I1108 08:59:40.193368 20039 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
I1108 08:59:40.193425 20039 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
I1108 08:59:40.193430 20039 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
I1108 08:59:40.215290 20040 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
I1108 08:59:40.215342 20040 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
I1108 08:59:40.215351 20040 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
I1108 08:59:40.691021 20040 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f68f8000000' with size 268435456
I1108 08:59:40.703954 20039 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f5050000000' with size 268435456
I1108 08:59:40.711398 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1108 08:59:40.711420 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
I1108 08:59:40.711424 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 2 with size 67108864
I1108 08:59:40.711426 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 3 with size 67108864
I1108 08:59:40.711430 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 4 with size 67108864
I1108 08:59:40.711433 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 5 with size 67108864
I1108 08:59:40.711435 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 6 with size 67108864
I1108 08:59:40.711437 20040 cuda_memory_manager.cc:107] CUDA memory pool is created on device 7 with size 67108864
I1108 08:59:40.718356 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1108 08:59:40.718371 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
I1108 08:59:40.718375 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 2 with size 67108864
I1108 08:59:40.718377 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 3 with size 67108864
I1108 08:59:40.718380 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 4 with size 67108864
I1108 08:59:40.718382 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 5 with size 67108864
I1108 08:59:40.718385 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 6 with size 67108864
I1108 08:59:40.718387 20039 cuda_memory_manager.cc:107] CUDA memory pool is created on device 7 with size 67108864
I1108 08:59:46.572046 20039 model_lifecycle.cc:462] loading: tensorrt_llm:1
I1108 08:59:46.572094 20039 model_lifecycle.cc:462] loading: preprocessing:1
I1108 08:59:46.572117 20039 model_lifecycle.cc:462] loading: postprocessing:1
I1108 08:59:46.580244 20040 model_lifecycle.cc:462] loading: tensorrt_llm:1
I1108 08:59:46.580287 20040 model_lifecycle.cc:462] loading: preprocessing:1
I1108 08:59:46.580319 20040 model_lifecycle.cc:462] loading: postprocessing:1
I1108 08:59:46.611591 20039 python_be.cc:2115] TRITONBACKEND_ModelInstanceInitialize: postprocessing_0_0 (CPU device 0)
I1108 08:59:46.611605 20039 python_be.cc:2115] TRITONBACKEND_ModelInstanceInitialize: preprocessing_0_0 (CPU device 0)
[TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
[TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
[TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
[TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
[TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
[TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
[TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
[TensorRT-LLM][INFO] Initializing MPI with thread mode 1
[TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
[TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
[TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
[TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
[TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
[TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
[TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
[TensorRT-LLM][INFO] Initializing MPI with thread mode 1
I1108 08:59:46.632181 20040 python_be.cc:2115] TRITONBACKEND_ModelInstanceInitialize: postprocessing_0_0 (CPU device 0)
I1108 08:59:46.632845 20040 python_be.cc:2115] TRITONBACKEND_ModelInstanceInitialize: preprocessing_0_0 (CPU device 0)
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
[TensorRT-LLM][INFO] MPI size: 2, rank: 1
[TensorRT-LLM][INFO] MPI size: 2, rank: 0
I1108 08:59:47.916477 20039 model_lifecycle.cc:819] successfully loaded 'postprocessing'
I1108 08:59:47.940582 20040 model_lifecycle.cc:819] successfully loaded 'postprocessing'
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
I1108 08:59:49.793689 20039 model_lifecycle.cc:819] successfully loaded 'preprocessing'
I1108 08:59:49.886355 20040 model_lifecycle.cc:819] successfully loaded 'preprocessing'
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 16
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 8
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
[TensorRT-LLM][INFO] Loaded engine size: 6990 MiB
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 16
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 8
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
[TensorRT-LLM][INFO] Loaded engine size: 6990 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 7719, GPU 17063 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 7720, GPU 17073 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 7719, GPU 14854 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 7720, GPU 14864 (MiB)
Failed, NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
Failed, NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
I1108 08:59:55.712208 20316 pb_stub.cc:1746]  Non-graceful termination detected. 
I1108 08:59:55.727274 20329 pb_stub.cc:1746]  Non-graceful termination detected. 
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[34324,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

Command to generate trtllm engine:
```bash
python build.py --model_dir /llama \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_inflight_batching \
                --paged_kv_cache \
                --remove_input_padding \
                --use_gemm_plugin float16 \
                --output_dir /tensorrtllm_backend/llama_A800/trt_engines/fp16/2-gpu/ \
                --world_size 2 \
                --tp_size 2
```

nvidia-smi:
Wed Nov  8 09:02:02 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A800-SXM4-80GB          On  | 00000000:0D:00.0 Off |                    0 |
| N/A   27C    P0              65W / 400W |   9091MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A800-SXM4-80GB          On  | 00000000:13:00.0 Off |                    0 |
| N/A   27C    P0              79W / 400W |   6881MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A800-SXM4-80GB          On  | 00000000:29:00.0 Off |                    0 |
| N/A   25C    P0              60W / 400W |   3675MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A800-SXM4-80GB          On  | 00000000:2D:00.0 Off |                    0 |
| N/A   25C    P0              59W / 400W |   2811MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A800-SXM4-80GB          On  | 00000000:C5:00.0 Off |                    0 |
| N/A   55C    P0             302W / 400W |  29011MiB / 81920MiB |     98%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A800-SXM4-80GB          On  | 00000000:CA:00.0 Off |                    0 |
| N/A   63C    P0             411W / 400W |  72695MiB / 81920MiB |     70%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A800-SXM4-80GB          On  | 00000000:E0:00.0 Off |                    0 |
| N/A   57C    P0             401W / 400W |  55755MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A800-SXM4-80GB          On  | 00000000:E4:00.0 Off |                    0 |
| N/A   36C    P0              58W / 400W |      5MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
(I don't know why I can't upload pictures)

When I run a simple test script for allreduce, it works normally.
```bash
import torch  

x = torch.rand(1024)  

proc_group = torch.distributed.init_process_group()
  
torch.distributed.all_reduce(x, group=proc_group)  

print(x)
```
```bash
 python -m torch.distributed.launch --nproc_per_node=4 test_allreduce.py
```
```bash
/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[2023-11-08 09:15:58,838] torch.distributed.run: [WARNING] 
[2023-11-08 09:15:58,838] torch.distributed.run: [WARNING] *****************************************
[2023-11-08 09:15:58,838] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-11-08 09:15:58,838] torch.distributed.run: [WARNING] *****************************************
tensor([1.4237, 1.8938, 2.8346,  ..., 1.0101, 1.8035, 2.7283])tensor([1.4237, 1.8938, 2.8346,  ..., 1.0101, 1.8035, 2.7283])tensor([1.4237, 1.8938, 2.8346,  ..., 1.0101, 1.8035, 2.7283])tensor([1.4237, 1.8938, 2.8346,  ..., 1.0101, 1.8035, 2.7283])
```

**Comment by byshiue** [comment]
Here is a related issue https://github.com/triton-inference-server/tensorrtllm_backend/issues/54, can you try the suggestion in the issue?

**Comment by PerkzZheng** [comment]
@yuehuayingxueluo as suggested in the [link](https://github.com/triton-inference-server/tensorrtllm_backend/issues/54), try to use nccl-tests with `NCCL_DEBUG=INFO`, and see what extra information we can get.

**Comment by yuehuayingxueluo** [comment]
@byshiue @PerkzZheng Thank you for your help. When I created Docker again, I remove the ‘--net host’ and the problem was resolved, but I don't know why.

**Comment by PerkzZheng** [comment]
> @byshiue @PerkzZheng Thank you for your help. When I created Docker again, I removed the ‘--net host’ and the problem was resolved, but I don't know why.

are you using vGPU ? it is good to know that removing --net host works. Also do you see any errors when running nccl-tests in the physical machine (not through containers) ?

**Comment by yuehuayingxueluo** [comment]
> > @byshiue @PerkzZheng Thank you for your help. When I created Docker again, I removed the ‘--net host’ and the problem was resolved, but I don't know why.
> 
> are you using vGPU ? it is good to know that removing --net host works. Also do you see any errors when running nccl-tests in the physical machine (not through containers) ?

![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/4ce29788-7bfd-4329-91a3-3cd74871f495)
Outside of the container, I executed "python -m torch.distributed.launch --nproc_per_node=4 test_allreduce.py" without any errors.

**Comment by PerkzZheng** [comment]
> > > @byshiue @PerkzZheng Thank you for your help. When I created Docker again, I removed the ‘--net host’ and the problem was resolved, but I don't know why.
> > 
> > 
> > are you using vGPU ? it is good to know that removing --net host works. Also do you see any errors when running nccl-tests in the physical machine (not through containers) ?
> 
> ![image](https://user-images.githubusercontent.com/26091437/281639338-4ce29788-7bfd-4329-91a3-3cd74871f495.png) Outside of the container, I executed "python -m torch.distributed.launch --nproc_per_node=4 test_allreduce.py" without any errors.

are you using the same nccl version inside and outside the container ?

**Comment by yuehuayingxueluo** [comment]
> > > > @byshiue @PerkzZheng Thank you for your help. When I created Docker again, I removed the ‘--net host’ and the problem was resolved, but I don't know why.
> > > 
> > > 
> > > are you using vGPU ? it is good to know that removing --net host works. Also do you see any errors when running nccl-tests in the physical machine (not through containers) ?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26091437/281639338-4ce29788-7bfd-4329-91a3-3cd74871f495.png) Outside of the container, I executed "python -m torch.distributed.launch --nproc_per_node=4 test_allreduce.py" without any errors.
> 
> are you using the same nccl version inside and outside the container ?

I use different torch versions inside and outside the container, as well as different nccl versions, which are (2, 14, 3) and (2, 18, 1), respectively.

**Comment by PerkzZheng** [comment]
if you have time, you can try upgrade the nccl version inside the container or just rebuild from source (https://github.com/NVIDIA/nccl). I suspect there are some bugs that have been fixed in recent NCCL versions. And if that doesn't exist after upgrading to the latest one, we will consider using the latest nccl version in our built docker images.

**Comment by yuehuayingxueluo** [comment]
> if you have time, you can try upgrade the nccl version inside the container or just rebuild from source (https://github.com/NVIDIA/nccl). I suspect there are some bugs that have been fixed in recent NCCL versions. And if that doesn't exist after upgrading to the latest one, we will consider using the latest nccl version in our built docker images.

Ok, I will try to upgrade it.

**Comment by yuehuayingxueluo** [comment]
I reinstalled NCCL according to the README of the NCCL repo, but the issue above still exists.

**Comment by PerkzZheng** [comment]
> I reinstalled NCCL according to the README of the NCCL repo, but the issue above still exists.

Thanks. I will let nccl team know, and see if they have any clues.
