### ISSUE TITLE
Launch triton server encounter error: [NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/sendPlugin.cpp:129 'invalid usage (run with NCCL_DEBUG=WARN for details)']

### ISSUE THREAD

**Issue by CN-COTER** [triton-inference-server/tensorrtllm_backend#170]
I got an error when loading engine. 

**Model type**: llama2-70B

**Engine build scripts:**

`
 CUDA_VISIBLE_DEVICES=4,5 python build.py \ 
--model_dir=/path_to_hf_ckpt \
--use_inflight_batching \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --enable_context_fmha \
                --output_dir /path_to_engine \
                --use_weight_only \
                --max_batch_size 1 \
                --tp_size 2 \
                --pp_size 4 \
                --world_size 8 \
                --weight_only_precision int4
`

**TP=2, world_size=8, PP=4**   

**launch triton server:**
NCCL_DEBUG=INFO CUDA_VISIBLE_DEVICES=1,3 python tensorrtllm_backend/scripts/launch_triton_server.py --world_size=8 --model_repo=/path_to_model_repo_trt_llm

**The error log is:**
`
           I1129 05:48:05.093906 5010 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.093944 5010 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.093948 5010 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.105379 5012 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.105410 5012 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.105413 5012 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.107318 5013 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.107344 5013 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.107347 5013 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.109362 5014 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.109386 5014 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.109390 5014 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.109865 5015 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.109894 5015 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.109898 5015 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.110653 5017 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.110675 5017 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.110679 5017 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.111273 5016 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.111295 5016 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.111298 5016 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:05.111508 5011 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
          I1129 05:48:05.111528 5011 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.15
          I1129 05:48:05.111532 5011 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.15
          I1129 05:48:06.179245 5010 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7fa542000000' with size 268435456
          I1129 05:48:06.181095 5014 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f2d82000000' with size 268435456
          I1129 05:48:06.181145 5016 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f2fc6000000' with size 268435456
          I1129 05:48:06.181561 5012 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f3a1a000000' with size 268435456
          I1129 05:48:06.182320 5017 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7fba02000000' with size 268435456
          I1129 05:48:06.373690 5013 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f9ede000000' with size 268435456
          I1129 05:48:06.374947 5015 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f985e000000' with size 268435456
          I1129 05:48:06.375322 5011 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7fb732000000' with size 268435456
          I1129 05:48:06.382440 5014 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.382446 5014 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.383824 5012 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.383838 5012 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.384847 5016 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.384863 5016 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.386832 5017 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.386839 5017 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.387181 5010 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.387195 5010 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.390259 5013 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.390275 5013 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.392846 5015 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.392863 5015 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:06.393729 5011 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
          I1129 05:48:06.393756 5011 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
          I1129 05:48:07.068859 5014 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.069833 5015 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.073904 5011 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.074024 5010 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.075406 5012 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.075552 5017 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.075909 5016 model_lifecycle.cc:462] loading: tensorrt_llm:1
          I1129 05:48:07.076959 5013 model_lifecycle.cc:462] loading: tensorrt_llm:1
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][WARNING] max_tokens_in_paged_kv_cache is not specified, will use default value
          [TensorRT-LLM][WARNING] batch_scheduler_policy parameter was not found or is invalid (must be max_utilization or guaranteed_no_evict)
          [TensorRT-LLM][WARNING] kv_cache_free_gpu_mem_fraction is not specified, will use default value of 0.85 or max_tokens_in_paged_kv_cache
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][WARNING] max_num_sequences is not specified, will be set to the TRT engine max_batch_size
          [TensorRT-LLM][WARNING] enable_trt_overlap is not specified, will be set to true
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
          [TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
          [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
          [TensorRT-LLM][INFO] MPI size: 8, rank: 2
          [TensorRT-LLM][INFO] MPI size: 8, rank: 1
          [TensorRT-LLM][INFO] MPI size: 8, rank: 0
          [TensorRT-LLM][INFO] MPI size: 8, rank: 5
          [TensorRT-LLM][INFO] MPI size: 8, rank: 4
          [TensorRT-LLM][INFO] MPI size: 8, rank: 7
          [TensorRT-LLM][INFO] MPI size: 8, rank: 3
          [TensorRT-LLM][INFO] MPI size: 8, rank: 6
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] Loaded engine size: 4085 MiB
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] Loaded engine size: 4085 MiB
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] Loaded engine size: 4085 MiB
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] Loaded engine size: 4393 MiB
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 2
          [TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 1
          [TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
          [TensorRT-LLM][INFO] Loaded engine size: 4085 MiB
          [TensorRT-LLM][INFO] Loaded engine size: 4393 MiB
          [TensorRT-LLM][INFO] Loaded engine size: 4701 MiB
          [TensorRT-LLM][INFO] Loaded engine size: 4701 MiB
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +7, GPU +10, now: CPU 4191, GPU 19602 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +7, GPU +20, now: CPU 4191, GPU 19612 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +7, GPU +4402, now: CPU 4191, GPU 19600 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +20, now: CPU 4192, GPU 19622 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +20, now: CPU 4192, GPU 19632 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 4192, GPU 19610 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 4498, GPU 19652 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 4500, GPU 19662 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 4498, GPU 19632 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 4500, GPU 19642 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +10, now: CPU 5422, GPU 19654 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +7, GPU +20, now: CPU 4191, GPU 19664 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +2, GPU +20, now: CPU 5424, GPU 19674 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +28, now: CPU 4192, GPU 19692 (MiB)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Bootstrap : Using eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin v6 (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO cudaDriverVersion 12020
          NCCL version 2.19.3+cuda12.3
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +10, now: CPU 5422, GPU 19674 (MiB)
          [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 5424, GPU 19684 (MiB)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO cudaDriverVersion 12020
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Bootstrap : Using eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin v6 (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO P2P plugin IBext
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO NET/Socket : Using [0]eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Using non-device net plugin version 0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Using network Socket
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO P2P plugin IBext
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO NET/Socket : Using [0]eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Using non-device net plugin version 0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Using network Socket
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO comm 0x7fb70e1a1f70 rank 1 nranks 2 cudaDev 1 nvmlDev 3 busId e3000 commId 0xbfc2f52bda86087e - Init START
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO comm 0x7fa51e1a3e80 rank 0 nranks 2 cudaDev 0 nvmlDev 2 busId ca000 commId 0xbfc2f52bda86087e - Init START
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Setting affinity for GPU 3 to ffffffff,00000000,ffffffff,00000000
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Setting affinity for GPU 2 to ffffffff,00000000,ffffffff,00000000
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO P2P Chunksize set to 131072
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Channel 00/02 :    0   1
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Channel 01/02 :    0   1
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO P2P Chunksize set to 131072
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Channel 00 : 1[3] -> 0[2] via SHM/direct/direct
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Channel 01 : 1[3] -> 0[2] via SHM/direct/direct
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Channel 00 : 0[2] -> 1[3] via SHM/direct/direct
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Channel 01 : 0[2] -> 1[3] via SHM/direct/direct
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Connected all rings
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Connected all trees
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Connected all rings
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Connected all trees
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO comm 0x7fa51e1a3e80 rank 0 nranks 2 cudaDev 0 nvmlDev 2 busId ca000 commId 0xbfc2f52bda86087e - Init COMPLETE
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO comm 0x7fb70e1a1f70 rank 1 nranks 2 cudaDev 1 nvmlDev 3 busId e3000 commId 0xbfc2f52bda86087e - Init COMPLETE
          NCCL version 2.19.3+cuda12.3
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Using non-device net plugin version 0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO Using network Socket
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Using non-device net plugin version 0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO Using network Socket
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO cudaDriverVersion 12020
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO Bootstrap : Using eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO cudaDriverVersion 12020
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO Bootstrap : Using eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin v6 (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin v6 (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v7 symbol.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v6)
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO P2P plugin IBext
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO P2P plugin IBext
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO NET/Socket : Using [0]eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO Using non-device net plugin version 0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO Using network Socket
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/IB : No device found.
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO NET/Socket : Using [0]eth0:10.108.8.30<0>
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO Using non-device net plugin version 0
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO Using network Socket
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO comm 0x7f9eb970aa60 rank 1 nranks 2 cudaDev 1 nvmlDev 3 busId e3000 commId 0xb3174048fe7edfef - Init START
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO comm 0x7fb46147d480 rank 0 nranks 2 cudaDev 1 nvmlDev 3 busId e3000 commId 0xb3174048fe7edfef - Init START
          
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] init.cc:824 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device e3000
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO init.cc:1396 -> 5
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO init.cc:1641 -> 5
          
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] init.cc:824 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device e3000
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO init.cc:1396 -> 5
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO init.cc:1641 -> 5
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5011:5092 [1] NCCL INFO init.cc:1679 -> 5
          Failed, NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/sendPlugin.cpp:129 'invalid usage (run with NCCL_DEBUG=WARN for details)'
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5013:5110 [1] NCCL INFO init.cc:1679 -> 5
          Failed, NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/recvPlugin.cpp:129 'invalid usage (run with NCCL_DEBUG=WARN for details)'
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO comm 0x7f39f570a8e0 rank 1 nranks 2 cudaDev 0 nvmlDev 2 busId ca000 commId 0x2ca118a142cc4635 - Init START
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO comm 0x7fa26147d290 rank 0 nranks 2 cudaDev 0 nvmlDev 2 busId ca000 commId 0x2ca118a142cc4635 - Init START
          
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] init.cc:824 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device ca000
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO init.cc:1396 -> 5
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO init.cc:1641 -> 5
          
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] init.cc:824 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device ca000
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO init.cc:1396 -> 5
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO init.cc:1641 -> 5
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5012:5098 [0] NCCL INFO init.cc:1679 -> 5
          Failed, NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/recvPlugin.cpp:129 'invalid usage (run with NCCL_DEBUG=WARN for details)'
          xllm3-milu2-neil-3-trt-llm-f7457bcc-xsv4v:5010:5090 [0] NCCL INFO init.cc:1679 -> 5
          Failed, NCCL error /app/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/sendPlugin.cpp:129 'invalid usage (run with NCCL_DEBUG=WARN for details)'
`

I just scaned all issiues in repo-trt-llm and repo-trt-llm-backend with related error and then got 3  issiues below
[https://github.com/triton-inference-server/tensorrtllm_backend/issues/54]
[https://github.com/triton-inference-server/tensorrtllm_backend/issues/103]
[https://github.com/NVIDIA/TensorRT-LLM/issues/213]

I have tried all of the methods, but got the above error.
Can anyone give me a hand?

**Comment by CN-COTER** [comment]
More details related to the circumstance above:
1.  The engine rank 0~8 all loaded according to log.   **Loaded engine size: 4085 MiB**
2.  The execution does not exit with any fault code, GPU memory is not released .The process seems enter dead lock.

**Comment by byshiue** [comment]
Why do you set `CUDA_VISIBLE_DEVICES=1,3` when you launch server?

**Comment by CN-COTER** [comment]
> Why do you set `CUDA_VISIBLE_DEVICES=1,3` when you launch server?
Just now i have solved the problem. 
The **world_size  must equal to gpu_num**.
I close this issue.
Thanks!
