### ISSUE TITLE
libnvinfer_plugin_tensorrt_llm.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Lzhang-hub** [triton-inference-server/tensorrtllm_backend#184]
I build docker with command in main branch
```
# Update the submodules
cd tensorrtllm_backend
git lfs install
git submodule update --init --recursive

# Use the Dockerfile to build the backend in a container
# For x86_64
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
```

Then `docker run -it --rm -v /model_path:/model_path triton_trt_llm:latest bash`
and `tritonserver --model-repository=/model_path`

get errer:

```
+----------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| Model          | Version | Status                                                                                                                                                |
+----------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| postprocessing | 1       | READY                                                                                                                                                 |
| preprocessing  | 1       | READY                                                                                                                                                 |
| tensorrt_llm   | 1       | UNAVAILABLE: Not found: unable to load shared library: libnvinfer_plugin_tensorrt_llm.so.9: cannot open shared object file: No such file or directory |
+----------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by byshiue** [comment]
Could you find `libnvinfer_plugin_tensorrt_llm.so` in `/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs`? 
If yes, you could add a soft link as workaround. We will consider how to fix it.

**Comment by byshiue** [comment]
Could you try latest main branch again? We have a update last Friday.

**Comment by Linzecong** [comment]
> Could you try latest main branch again? We have a update last Friday.

it works. thanks~!

**Comment by Linzecong** [comment]
sorry, but it doesn't work when world_size is 2. world_size 1 is ok.

[fd7bb8667392:01104] [10] /app/inflight_batcher_llm/../tensorrt_llm/cpp/build/tensorrt_llm/plugins/libnvinfer_plugin_tensorrt_llm.so.9(_ZN12tensorrt_llm7plugins15AllreducePlugin10initializeEv+0x760)[0x7f20c5c1d400]

here's my build config, baichuan13b

`
    --use_gemm_plugin
    --use_gpt_attention_plugin
    --world_size 2
    --use_inflight_batching
    --paged_kv_cache
    --remove_input_padding
    --use_weight_only
    --weight_only_precision int4
`

**Comment by byshiue** [comment]
Please share the full reproduced scripts and the full error log.

**Comment by byshiue** [comment]
It looks issue on nccl. Could you trying running nccl test in https://github.com/NVIDIA/nccl-tests?

**Comment by Linzecong** [comment]
After running the test, I found that the problem was due to insufficient shared memory settings. After I increased --shm-size, the problem was solved. Thank you so much!

**Comment by byshiue** [comment]
Thank you for the update. Close this bug because the issue is resolved.
