### ISSUE TITLE
triton start tensort_llm out of memery

### ISSUE THREAD

**Issue by moseshu** [triton-inference-server/tensorrtllm_backend#281]
tensorRT-LLM=v0.7.1
tensortllm_backend=v0.7.1
base_model=mistral-7b
```
this is the build script
python3 build.py --model_dir ${base_model}  --dtype float16 \
      --use_gpt_attention_plugin float16  \
      --use_gemm_plugin float16  \
      --output_dir "saved_model/2-gpu"  \
      --max_batch_size "32" --max_input_len 32256 --max_output_len 16384 \
      --use_rmsnorm_plugin float16  \
      --remove_input_padding \
      --enable_context_fmha \
      --use_inflight_batching \
      --paged_kv_cache \
      --max_num_tokens "2048" \
      --world_size 2 \
      --tp_size 2 
```
triton start script is 
```
python3 launch_triton_server.py --world_size=2 --model_repo=./triton_model_repo 

```
### the error is 

Model 'tensorrt_llm' loading failed with error: version 1 is at UNAVAILABLE state: Internal: unexpected error when creating modelInstanceState: [TensorRT-LLM][ERROR] CUDA runtime error in ::cudaMallocAsync(ptr, n, mCudaStream->get()): out of memory (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmBuffers.h:112)

**Comment by wind417588** [comment]
@moseshu getting the same error with llama 7b. how did you solve it?

**Comment by wind417588** [comment]
@moseshu  Thanks. I solved it by adjusting the max_batch_size value when compiled engine.
