### ISSUE TITLE
Failed, NCCL error  'internal error - please report this is sue to the NCCL developers'

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [triton-inference-server/tensorrtllm_backend#46]
There was an error reported. 

python3 scripts/launch_triton_server.py --world_size=2 --model_repo=./all_models/inflight_batcher_llm/ 

<img width="1511" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/6f87923f-2bf1-492b-bc02-eb97e404d3b1">

Transformational Model

`python examples/baichuan/build.py --model_version v2_13b --max_output_len=1024 --model_dir ./models/Baichuan2-13B-Chat/ --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --world_size 2  --remove_input_padding  --use_inflight_batching --paged_kv_cache --output_dir ./models/tmp/baichuan_v2_13b/trt_engines/fp16/2-gpu/`

Adapt  all_models/inflight_batcher_llm  files
```
all_models/inflight_batcher_llm/postprocessing/1/model.py  L65
self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir**, use_fast=False, trust_remote_code=True**) 
all_models/inflight_batcher_llm/preprocessing/1/model.py  L69
self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir**, use_fast=False, trust_remote_code=True**) 
```

docker run  
`docker run --rm -it --net host --shm-size=2g --ulimit memlock=-1 --ulimit stack=67108864 --gpus all -v $(pwd)/all_models:/app/all_models -v $(pwd)/models:/models  triton_trt_llm bash`

**Comment by byshiue** [comment]
Can you try setting larger shm when you launch docker image? Besides, can you run nccl test?

**Comment by callmezhangchenchenokay** [comment]
Set shm to 4g, and both 8g will report the same error as 2g

according to  https://github.com/NVIDIA/nccl， test nccl-test erro

<img width="1176" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/65381607-94c1-4120-90db-24f7839139ac">

So there's a problem with the built docker
When I built it, there was no error,

**Comment by byshiue** [comment]
Do you use the docker file provided by tensorrt_llm backend to build the docker? Can you share your scripts to build the docker?

**Comment by callmezhangchenchenokay** [comment]
```
cd ..
git clone -b release/0.5.0 git@github.com:triton-inference-server/tensorrtllm_backend.git
cd tensorrtllm_backend
git submodule update --init --recursive
git lfs install
git lfs pull
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
```
I use the above script to build the docker
My host is Centos 7, but the built Docker result is Ubuntu, which I feel has little impact

Additionally, I tried the single GPU running model and it went smoothly


When I use this client code，form (https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/)
```
import numpy as np
import tritonclient.http as httpclient
from tritonclient.utils import np_to_triton_dtype
 
def prepare_tensor(name, input):
    t = httpclient.InferInput(name, input.shape,
                               np_to_triton_dtype(input.dtype))
    t.set_data_from_numpy(input)
    return t
 
TRITON_URL = "localhost:8000"   
client = httpclient.InferenceServerClient(TRITON_URL)
 
prompt = "How do I count to nine in French?"
 
inputs = [
    prepare_tensor("text_input", np.array([[prompt]], dtype=object)),
    prepare_tensor("max_tokens", np.array([[100]], dtype=np.uint32)),
    prepare_tensor("bad_words", np.array([[""]], dtype=object)),
    prepare_tensor("stop_words", np.array([[""]], dtype=object))
]
 
result = client.infer("ensemble", inputs)
print(result)
```
It got this error  
<img width="1393" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/b6fc1c27-8f6b-4643-96f7-d9715b2aa3d3">

When I use this client command， 
`python3 inflight_batcher_llm/client/inflight_batcher_llm_client.py --request-output-len 200 --tokenizer_dir /models/Baichuan2-13B-Chat/`
I'm a bit confused here, why do you still need to pass it on? Tokenizer_ The dir parameter clearly indicates that preprocessing/1/model.py has already been preprocessed


It got this error, output is empty.   
<img width="1488" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/63191c7b-b895-4f4d-851d-af405c76d17b">

**Comment by callmezhangchenchenokay** [comment]
the problem of single GPU client, have already been solved
Because：After entering the Docker by default, there is an /app/inflight_batcher_llm, Don't use this,
 use this file https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/tools/inflight_batcher_llm/end_to_end_streaming_client.py

**Comment by callmezhangchenchenokay** [comment]
the problem of nccl,have already been solved
 Because：When I was compiling nccl, I made a mistake in writing the compilation option
  make -j src.build NVCC_GENCODE="-gencode=arch=compute_70,code=sm_70"
<img width="1458" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/6fc7a0e1-18f2-4fcf-9155-8fccaa21abf7">

**Comment by callmezhangchenchenokay** [comment]
I thought he would succeed, but it wasn't that easy
And now the error is like this

<img width="1504" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/9c78f937-831b-4249-988a-5e471b7dfb1a">

Here is the complete log
[erro.log](https://github.com/triton-inference-server/tensorrtllm_backend/files/13184949/erro.log)


@byshiue  

I'm going to trouble you again here

I will also look for any solutions

**Comment by callmezhangchenchenokay** [comment]
Hi @byshiue
 
I confirmed that the docker I built was fine, and  nccl is good
I tried running run.py in this docker and it worked fine

`mpirun -n 2 --allow-run-as-root python ./tensorrt_llm/examples/baichuan/run.py --model_version v2_13b --max_output_len=1024 --tokenizer_dir=/models/Baichuan2-13B-Chat/ --engine_dir=./all_models/inflight_batcher_llm/tensorrt_llm/1/`

<img width="1498" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/407624d0-0a26-4ba0-8861-77ed43e4fa52">

**Comment by byshiue** [comment]
Thank you for the update. Close this bug. Feel free to repoen if needed.

**Comment by callmezhangchenchenokay** [comment]
@byshiue  It's not! The problem hasn't been solved yet
Running ./tensorrt_llm/examples/baichuan/run.py with two Gpus in docker is now normal
However, Triton cannot use this service, and will still report the problem of nccl
